version: 2
registries:
  npm-registry:
    type: npm-registry
    url: https://registry.npmjs.org
    token: ${{secrets.NPM_TOKEN}}
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    registries:
      - npm-registry
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
