branches:
  - name: main
    protection:
      required_status_checks:
        strict: true
        contexts:
          - CI / lint
          - CI / typecheck
          - CI / test
          - CI / e2e
          - CI / lighthouse
          - Accessibility / a11y
