import { resolveIconName } from './index';

const APP_ICON_MAP = {
  'qr': 'qr',
  'ascii-art': 'terminal',
  'clipboard-manager': 'note',
  'figlet': 'terminal',
  'quote': 'message',
  'project-gallery': 'grid',
  'input-lab': 'lab',
  '2048': 'game-puzzle',
  'asteroids': 'game-arcade',
  'battleship': 'radar',
  'blackjack': 'game-card',
  'breakout': 'game-arcade',
  'car-racer': 'game-runner',
  'lane-runner': 'game-runner',
  'checkers': 'game-puzzle',
  'chess': 'analysis',
  'connect-four': 'game-puzzle',
  'frogger': 'game-runner',
  'hangman': 'document',
  'memory': 'game-puzzle',
  'minesweeper': 'analysis',
  'pacman': 'game-arcade',
  'platformer': 'game-runner',
  'pong': 'game-arcade',
  'reversi': 'game-puzzle',
  'simon': 'music',
  'snake': 'game-runner',
  'sokoban': 'game-puzzle',
  'solitaire': 'game-card',
  'tictactoe': 'game-puzzle',
  'tetris': 'game-puzzle',
  'tower-defense': 'shield',
  'word-search': 'document',
  'wordle': 'document',
  'nonogram': 'game-puzzle',
  'space-invaders': 'game-arcade',
  'sudoku': 'game-puzzle',
  'flappy-bird': 'game-runner',
  'candy-crush': 'game-arcade',
  'gomoku': 'game-puzzle',
  'pinball': 'game-arcade',
  'chrome': 'browser',
  'calculator': 'calculator',
  'terminal': 'terminal',
  'vscode': 'code',
  'x': 'message',
  'spotify': 'music',
  'youtube': 'video',
  'beef': 'bug',
  'about': 'profile',
  'settings': 'settings',
  'files': 'folder',
  'resource-monitor': 'graph',
  'screen-recorder': 'camera',
  'ettercap': 'network',
  'ble-sensor': 'wifi',
  'metasploit': 'shield',
  'wireshark': 'radar',
  'todoist': 'checklist',
  'sticky_notes': 'note',
  'trash': 'trash',
  'gedit': 'document',
  'converter': 'analysis',
  'kismet': 'radar',
  'nikto': 'analysis',
  'autopsy': 'analysis',
  'plugin-manager': 'chip',
  'reaver': 'network',
  'nessus': 'shield',
  'ghidra': 'chip',
  'mimikatz': 'lock',
  'mimikatz/offline': 'lock',
  'ssh': 'terminal',
  'http': 'network',
  'html-rewriter': 'code',
  'contact': 'message',
  'hydra': 'shield',
  'nmap-nse': 'radar',
  'weather': 'weather',
  'weather-widget': 'weather',
  'serial-terminal': 'terminal',
  'radare2': 'chip',
  'volatility': 'graph',
  'hashcat': 'chip',
  'msf-post': 'shield',
  'evidence-vault': 'lock',
  'dsniff': 'network',
  'john': 'lock',
  'openvas': 'shield',
  'recon-ng': 'radar',
  'security-tools': 'shield',
} as const;

export type AppIconId = keyof typeof APP_ICON_MAP;

export const getAppIcon = (id: string, fallback = 'app') => {
  const candidate = (APP_ICON_MAP as Record<string, string>)[id];
  return resolveIconName(candidate ?? fallback);
};

export const APP_ICON_MAP_ENTRIES = APP_ICON_MAP;

