yarnPath: .yarn/releases/yarn-3.8.7.cjs
logFilters:
  - level: discard
    pattern: deprecated sourcemap-codec@1.4.8
  - level: discard
    pattern: Glob versions prior to v9 are no longer supported
  - level: discard
    pattern: "inflight@1.0.6: This module is not supported"

nodeLinker: node-modules
