nodeLinker: node-modules

logFilters:
  - pattern: "deprecated sourcemap-codec@1.4.8"
    level: discard
  - pattern: "Glob versions prior to v9 are no longer supported"
    level: discard
  - pattern: "inflight@1.0.6: This module is not supported"
    level: discard
  - pattern: "source-map@0.8.0-beta.0: The work that was done in this beta branch won't be included in future versions"
    level: discard

