yarnPath: .yarn/releases/yarn-4.9.2.cjs
nodeLinker: node-modules

logFilters:
  - pattern: "deprecated sourcemap-codec@1.4.8"
    level: discard
  - pattern: "Glob versions prior to v9 are no longer supported"
    level: discard
  - pattern: "inflight@1.0.6: This module is not supported"
    level: discard
  - pattern: "The engine \"bare\" appears to be invalid."
    level: discard
  - pattern: "Resolution field \"magic-string@*\" is incompatible with requested version"
    level: info

packageExtensions:
  "3d-force-graph-ar@*":
    dependencies:
      aframe: "*"
  "3d-force-graph-vr@*":
    dependencies:
      aframe: "*"
  "aframe-forcegraph-component@*":
    dependencies:
      aframe: "*"
      three: "*"
  "react-force-graph@*":
    dependencies:
      aframe: "*"

