yarnPath: .yarn/releases/yarn-4.9.2.cjs
nodeLinker: node-modules

logFilters:
  - pattern: "deprecated sourcemap-codec@1.4.8"
    level: discard
  - pattern: "Glob versions prior to v9 are no longer supported"
    level: discard
  - pattern: "inflight@1.0.6: This module is not supported"
    level: discard
  - pattern: "The engine \"bare\" appears to be invalid."
    level: discard
  - pattern: "Resolution field \"magic-string@*\" is incompatible with requested version"
    level: info

packageExtensions:
  "3d-force-graph-ar@*":
    # // Provide 3d-force-graph-ar with our aframe/three peers until upstream declares them (react-force-graph#147).
    peerDependencies:
      aframe: "*"
      three: "*"
  "3d-force-graph-vr@*":
    # // VR bindings ship an aframe peer but still miss three; keep Yarn from flagging the gap (react-force-graph#147).
    peerDependencies:
      three: "*"
  "aframe-forcegraph-component@*":
    # // Component bundles three-forcegraph but forgets to list three as a peer; keep Yarn quiet (see package.json in vasturiano/aframe-forcegraph-component@3.3.0).
    peerDependencies:
      three: "*"
  "react-force-graph@*":
    # // React bindings rely on the 3D/VR layers which expect aframe and three; track upstream discussion in https://github.com/vasturiano/react-force-graph/issues/147.
    peerDependencies:
      aframe: "*"
      three: "*"

