// Security headers configuration for Next.js.
// The previous configuration blocked external images and prevented
// embedding the resume PDF. This version allows required resources while
// keeping sensible defaults.

const ContentSecurityPolicy = [
  "default-src 'self'",
  // Allow external images and data URIs for badges/icons
  "img-src 'self' https: data:",
  // Permit inline styles generated by React components
  "style-src 'self' 'unsafe-inline'",
  // Allow this site to embed its own resources (resume PDF)
  "frame-ancestors 'self'",
].join('; ');

const securityHeaders = [
  {
    key: 'Content-Security-Policy',
    value: ContentSecurityPolicy,
  },
  {
    key: 'X-Content-Type-Options',
    value: 'nosniff',
  },
  {
    key: 'Referrer-Policy',
    value: 'strict-origin-when-cross-origin',
  },
  {
    key: 'Permissions-Policy',
    value: 'camera=(), microphone=(), geolocation=()',
  },
  {
    // Allow same-origin framing so the PDF resume renders in an <object>
    key: 'X-Frame-Options',
    value: 'SAMEORIGIN',
  },
];

module.exports = {
  async headers() {
    return [
      {
        source: '/(.*)',
        headers: securityHeaders,
      },
    ];
  },
};

