const plugin = require('tailwindcss/plugin');

module.exports = {
  darkMode: 'class',
  mode: 'jit',
  content: [
    './pages/**/*.{js,ts,jsx,tsx}',
    './components/**/*.{js,ts,jsx,tsx}',
    './apps/**/*.{js,ts,jsx,tsx}',
    './hooks/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      screens: {
        '3xl': '1920px',
      },
      colors: {
        background: 'var(--color-bg)',
        surface: 'var(--color-surface)',
        'surface-alt': 'var(--color-surface-alt)',
        muted: 'var(--color-muted)',
        border: 'var(--color-border)',
        'border-strong': 'var(--color-border-strong)',
        text: 'var(--color-text)',
        'text-muted': 'var(--color-text-muted)',
        accent: 'var(--color-accent)',
        'accent-secondary': 'var(--color-accent-secondary)',
        'window-title': 'var(--color-window-title)',
        dark: 'var(--color-dark)',
        terminal: 'var(--color-terminal)',
        overlay: 'var(--kali-bg)',
        'kali-primary': {
          DEFAULT: 'var(--color-primary)',
          50: 'var(--color-kali-primary-50)',
          100: 'var(--color-kali-primary-100)',
          200: 'var(--color-kali-primary-200)',
          300: 'var(--color-kali-primary-300)',
          400: 'var(--color-kali-primary-400)',
          500: 'var(--color-kali-primary-500)',
          600: 'var(--color-kali-primary-600)',
          700: 'var(--color-kali-primary-700)',
          800: 'var(--color-kali-primary-800)',
          900: 'var(--color-kali-primary-900)',
          950: 'var(--color-kali-primary-950)',
        },
        'kali-secondary': {
          DEFAULT: 'var(--color-accent-secondary)',
          50: 'var(--color-kali-secondary-50)',
          100: 'var(--color-kali-secondary-100)',
          200: 'var(--color-kali-secondary-200)',
          300: 'var(--color-kali-secondary-300)',
          400: 'var(--color-kali-secondary-400)',
          500: 'var(--color-kali-secondary-500)',
          600: 'var(--color-kali-secondary-600)',
          700: 'var(--color-kali-secondary-700)',
          800: 'var(--color-kali-secondary-800)',
          900: 'var(--color-kali-secondary-900)',
          950: 'var(--color-kali-secondary-950)',
        },
        'kali-neutral': {
          DEFAULT: 'var(--color-kali-neutral-500)',
          50: 'var(--color-kali-neutral-50)',
          100: 'var(--color-kali-neutral-100)',
          200: 'var(--color-kali-neutral-200)',
          300: 'var(--color-kali-neutral-300)',
          400: 'var(--color-kali-neutral-400)',
          500: 'var(--color-kali-neutral-500)',
          600: 'var(--color-kali-neutral-600)',
          700: 'var(--color-kali-neutral-700)',
          800: 'var(--color-kali-neutral-800)',
          900: 'var(--color-kali-neutral-900)',
          950: 'var(--color-kali-neutral-950)',
        },
        // Legacy aliases to ease migration from Ubuntu naming
        'ub-grey': 'var(--color-bg)',
        'ub-warm-grey': 'var(--color-neutral-warm)',
        'ub-cool-grey': 'var(--color-surface)',
        'ub-lite-abrgn': 'var(--color-surface-alt)',
        'ub-med-abrgn': 'var(--color-surface)',
        'ub-drk-abrgn': 'var(--color-dark)',
        'ub-window-title': 'var(--color-window-title)',
        'ub-orange': 'var(--color-primary)',
        'ub-primary': 'var(--color-primary)',
        'ub-blue': 'var(--color-kali-primary-600)',
        'ub-green': 'var(--color-status-success)',
        'ub-yellow': 'var(--color-status-warning)',
        'ub-red': 'var(--color-status-danger)',
        'ub-black': 'var(--color-inverse)',
        'ub-dark': 'var(--color-dark)',
        'ub-dark-grey': 'var(--color-muted)',
        'ub-dracula': 'var(--color-accent-secondary)',
        'ub-dracula-dark': 'var(--color-accent-secondary-strong)',
        'ub-gedit-dark': 'var(--color-gedit-base)',
        'ub-gedit-light': 'var(--color-gedit-dark)',
        'ub-gedit-darker': 'var(--color-gedit-darker)',
        'ub-border-orange': 'var(--color-primary-strong)',
        'ub-gray': {
          DEFAULT: 'var(--color-kali-neutral-500)',
          50: 'var(--color-kali-neutral-50)',
          100: 'var(--color-kali-neutral-100)',
          200: 'var(--color-kali-neutral-200)',
          300: 'var(--color-kali-neutral-300)',
          400: 'var(--color-kali-neutral-400)',
          500: 'var(--color-kali-neutral-500)',
          600: 'var(--color-kali-neutral-600)',
          700: 'var(--color-kali-neutral-700)',
          800: 'var(--color-kali-neutral-800)',
          900: 'var(--color-kali-neutral-900)',
          950: 'var(--color-kali-neutral-950)',
        },
        'ubt-grey': 'var(--color-neutral-light)',
        'ubt-gray': 'var(--color-neutral-light)',
        'ubt-warm-grey': 'var(--color-neutral-warm)',
        'ubt-cool-grey': 'var(--color-neutral-cool)',
        'ubt-blue': 'var(--color-kali-primary-300)',
        'ubt-green': 'var(--color-status-success)',
        'ubt-gedit-orange': 'var(--color-status-warning)',
        'ubt-gedit-blue': 'var(--color-status-info)',
        'ubt-gedit-dark': 'var(--color-gedit-dark)',
      },
      fontFamily: {
        ubuntu: ['Ubuntu', 'sans-serif'],
      },
      minWidth: {
        '0': '0',
        '1/4': '25%',
        '1/2': '50%',
        '3/4': '75%',
        'full': '100%',
      },
      minHeight: {
        '0': '0',
        '1/4': '25%',
        '1/2': '50%',
        '3/4': '75%',
        'full': '100%',
      },
      zIndex: {
        '-10': '-10',
      },
      width: {
        'app-icon': '64px',
        'app-icon-lg': '96px',
        'tray-icon': '16px',
        'tray-icon-lg': '32px',
      },
      height: {
        'app-icon': '64px',
        'app-icon-lg': '96px',
        'tray-icon': '16px',
        'tray-icon-lg': '32px',
      },
      keyframes: {
        glow: {
          '0%, 100%': { boxShadow: '0 0 0px theme("colors.amber.400")' },
          '50%': { boxShadow: '0 0 8px theme("colors.amber.400")' },
        },
        flourish: {
          '0%': { transform: 'scale(0.8) rotate(0deg)', opacity: '0' },
          '50%': { transform: 'scale(1.2) rotate(0deg)', opacity: '1' },
          '100%': { transform: 'scale(1) rotate(360deg)', opacity: '1' },
        },
        mine: {
          '0%': { transform: 'translate(0,0) scale(1)', backgroundColor: 'theme("colors.red.500")' },
          '50%': {
            transform: 'translate(-1px,1px) scale(1.1)',
            backgroundColor: 'theme("colors.red.700")',
          },
          '100%': { transform: 'translate(0,0) scale(1)', backgroundColor: 'theme("colors.red.500")' },
        },
      },
      animation: {
        glow: 'glow 1s ease-in-out infinite',
        flourish: 'flourish 0.6s ease-out',
        mine: 'mine 0.4s ease-in-out',
      },
    },
  },
  plugins: [
    plugin(function ({ addUtilities }) {
      const cols = {};
      for (let i = 1; i <= 12; i++) {
        const width = `${(i / 12) * 100}%`;
        cols[`.col-${i}`] = { flex: `0 0 ${width}`, maxWidth: width };
        if (i < 12) {
          cols[`.offset-${i}`] = { marginLeft: width };
        }
      }
      addUtilities(cols, ['responsive']);
    }),
  ],
};
