// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = never
type AppRouteHandlerRoutes = "/api/log-client-error"
type PageRoutes = "/" | "/admin/messages" | "/apps" | "/apps/2048" | "/apps/ascii-art" | "/apps/autopsy" | "/apps/beef" | "/apps/blackjack" | "/apps/calculator" | "/apps/checkers" | "/apps/connect-four" | "/apps/contact" | "/apps/converter" | "/apps/figlet" | "/apps/http" | "/apps/input-lab" | "/apps/john" | "/apps/kismet" | "/apps/metasploit" | "/apps/metasploit-post" | "/apps/mimikatz/offline" | "/apps/minesweeper" | "/apps/nmap-nse" | "/apps/password_generator" | "/apps/phaser_matter" | "/apps/pinball" | "/apps/project-gallery" | "/apps/qr" | "/apps/settings" | "/apps/simon" | "/apps/sokoban" | "/apps/solitaire" | "/apps/spotify" | "/apps/ssh" | "/apps/sticky_notes" | "/apps/subnet-calculator" | "/apps/timer_stopwatch" | "/apps/tower-defense" | "/apps/volatility" | "/apps/vscode" | "/apps/weather" | "/apps/weather_widget" | "/apps/wireshark" | "/apps/word_search" | "/apps/x" | "/daily-quote" | "/dummy-form" | "/gamepad-calibration" | "/games/blackjack" | "/games/blackjack/trainer" | "/games/breakout/editor" | "/hook-flow" | "/hydra-preview" | "/input-hub" | "/keyboard-reference" | "/module-workspace" | "/nessus-dashboard" | "/nessus-report" | "/network-topology" | "/nikto-report" | "/notes" | "/popular-modules" | "/post_exploitation" | "/profile" | "/qr" | "/qr/vcard" | "/recon/graph" | "/security-education" | "/sekurlsa_logonpasswords" | "/share-target" | "/spoofing" | "/ui/settings/theme" | "/video-gallery" | "/wps-attack"
type LayoutRoutes = never
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/admin/messages": {}
  "/api/log-client-error": {}
  "/apps": {}
  "/apps/2048": {}
  "/apps/ascii-art": {}
  "/apps/autopsy": {}
  "/apps/beef": {}
  "/apps/blackjack": {}
  "/apps/calculator": {}
  "/apps/checkers": {}
  "/apps/connect-four": {}
  "/apps/contact": {}
  "/apps/converter": {}
  "/apps/figlet": {}
  "/apps/http": {}
  "/apps/input-lab": {}
  "/apps/john": {}
  "/apps/kismet": {}
  "/apps/metasploit": {}
  "/apps/metasploit-post": {}
  "/apps/mimikatz/offline": {}
  "/apps/minesweeper": {}
  "/apps/nmap-nse": {}
  "/apps/password_generator": {}
  "/apps/phaser_matter": {}
  "/apps/pinball": {}
  "/apps/project-gallery": {}
  "/apps/qr": {}
  "/apps/settings": {}
  "/apps/simon": {}
  "/apps/sokoban": {}
  "/apps/solitaire": {}
  "/apps/spotify": {}
  "/apps/ssh": {}
  "/apps/sticky_notes": {}
  "/apps/subnet-calculator": {}
  "/apps/timer_stopwatch": {}
  "/apps/tower-defense": {}
  "/apps/volatility": {}
  "/apps/vscode": {}
  "/apps/weather": {}
  "/apps/weather_widget": {}
  "/apps/wireshark": {}
  "/apps/word_search": {}
  "/apps/x": {}
  "/daily-quote": {}
  "/dummy-form": {}
  "/gamepad-calibration": {}
  "/games/blackjack": {}
  "/games/blackjack/trainer": {}
  "/games/breakout/editor": {}
  "/hook-flow": {}
  "/hydra-preview": {}
  "/input-hub": {}
  "/keyboard-reference": {}
  "/module-workspace": {}
  "/nessus-dashboard": {}
  "/nessus-report": {}
  "/network-topology": {}
  "/nikto-report": {}
  "/notes": {}
  "/popular-modules": {}
  "/post_exploitation": {}
  "/profile": {}
  "/qr": {}
  "/qr/vcard": {}
  "/recon/graph": {}
  "/security-education": {}
  "/sekurlsa_logonpasswords": {}
  "/share-target": {}
  "/spoofing": {}
  "/ui/settings/theme": {}
  "/video-gallery": {}
  "/wps-attack": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
