import { HostReport } from './types';

export const sampleData: HostReport[] = [
  {
    host: '192.168.56.10',
    risk: 'High',
    vulns: [
      {
        id: 'CVE-2023-0001',
        name: 'OpenSSL Buffer Overflow',
        cvss: 9.8,
        epss: 0.97,
        description: 'Remote code execution via crafted packet.',
        remediation: 'Update OpenSSL to the latest version',
        detectedAt: '2024-04-01',
      },
      {
        id: 'CVE-2022-1234',
        name: 'Apache Path Traversal',
        cvss: 7.5,
        epss: 0.32,
        description: 'Improper input validation allows directory traversal.',
        remediation: 'Apply vendor patch for Apache',
        detectedAt: '2024-04-01',
      },
      {
        id: 'CVE-2024-2222',
        name: 'Deprecated TLS Configuration',
        cvss: 5.6,
        epss: 0.14,
        description: 'Server negotiates TLS 1.0 enabling downgrade attacks.',
        remediation: 'Disable legacy TLS versions and ciphers',
        detectedAt: '2024-04-03',
      },
      {
        id: 'CVE-2024-3333',
        name: 'Weak Admin Portal Authentication',
        cvss: 8.1,
        epss: 0.41,
        description: 'Administrative portal allows brute-force enumeration.',
        remediation: 'Enable MFA and account lockout policies',
        detectedAt: '2024-04-04',
      },
    ],
  },
  {
    host: '192.168.56.20',
    risk: 'Medium',
    vulns: [
      {
        id: 'CVE-2021-9999',
        name: 'SSH Weak Cipher',
        cvss: 5.0,
        epss: 0.04,
        description: 'Server supports deprecated SSH ciphers.',
        remediation: 'Disable weak ciphers in SSH config',
        detectedAt: '2024-04-02',
      },
      {
        id: 'CVE-2023-4444',
        name: 'Verbose Error Messages',
        cvss: 3.9,
        epss: 0.08,
        description: 'Application discloses stack traces to unauthenticated users.',
        remediation: 'Disable verbose errors in production',
        detectedAt: '2024-04-02',
      },
      {
        id: 'CVE-2024-5555',
        name: 'Outdated Database Patch Level',
        cvss: 6.2,
        epss: 0.27,
        description: 'Database engine missing cumulative security updates.',
        remediation: 'Apply the latest vendor security rollup',
        detectedAt: '2024-04-05',
      },
    ],
  },
  {
    host: '192.168.56.30',
    risk: 'Critical',
    vulns: [
      {
        id: 'CVE-2020-7777',
        name: 'Unauthenticated Remote Command Execution',
        cvss: 9.4,
        epss: 0.89,
        description: 'Remote attackers can execute arbitrary commands.',
        remediation: 'Take system offline and apply vendor patches immediately',
        detectedAt: '2024-04-03',
      },
      {
        id: 'CVE-2022-8888',
        name: 'Privilege Escalation via Kernel Module',
        cvss: 7.9,
        epss: 0.52,
        description: 'Local users can escalate privileges to root.',
        remediation: 'Rebuild kernel with patched module',
        detectedAt: '2024-04-05',
      },
      {
        id: 'CVE-2024-0009',
        name: 'Remote Code Execution in Scheduler Service',
        cvss: 9.1,
        epss: 0.73,
        description: 'Scheduler service processes untrusted job payloads.',
        remediation: 'Restrict job inputs and deploy patched service binary',
        detectedAt: '2024-04-06',
      },
    ],
  },
  {
    host: '192.168.56.40',
    risk: 'Low',
    vulns: [
      {
        id: 'CVE-2021-1010',
        name: 'Informational Banner Disclosure',
        cvss: 2.7,
        epss: 0.02,
        description: 'Service banner reveals OS and product version.',
        remediation: 'Disable banner or replace with generic message',
        detectedAt: '2024-04-04',
      },
    ],
  },
];
