const EMBED_FRAME_ALLOWED_ORIGINS = [
  'https://vercel.live',
  'https://stackblitz.com',
  'https://www.youtube-nocookie.com',
  'https://open.spotify.com',
  'https://todoist.com',
  'https://embed.todoist.com',
  'https://www.kali.org',
  'https://www.offsec.com',
  'https://www.exploit-db.com',
  'https://forums.kali.org',
  'https://developer.mozilla.org',
  'https://en.wikipedia.org',
  'https://www.google.com',
  'https://*.google.com',
  'https://example.com',
  'https://platform.twitter.com',
  'https://embed.x.com',
  'https://syndication.twitter.com',
  'https://cdn.syndication.twimg.com',
  'https://*.twitter.com',
  'https://*.x.com',
  'https://twitter.com',
  'https://x.com',
];

module.exports = { EMBED_FRAME_ALLOWED_ORIGINS };
