import type { CalendarEvent } from './types';
import { addDays, setTime, startOfDay } from './utils';

const today = startOfDay(new Date());

export const sampleEvents: CalendarEvent[] = [
  {
    id: 'ops-standup',
    title: 'Operations Stand-up',
    start: setTime(today, 9, 0),
    end: setTime(today, 9, 30),
    location: 'SOC bridge',
    description: 'Quick update on active investigations and escalations.',
    category: 'operations',
  },
  {
    id: 'threat-workshop',
    title: 'Threat Hunting Workshop',
    start: setTime(addDays(today, 1), 13, 0),
    end: setTime(addDays(today, 1), 15, 0),
    location: 'Research lab',
    description: 'Hands-on lab session exploring new hunt hypotheses.',
    category: 'research',
  },
  {
    id: 'retro',
    title: 'Client Retrospective',
    start: setTime(addDays(today, 2), 11, 0),
    end: setTime(addDays(today, 2), 12, 0),
    location: 'Video conference',
    description: 'Share lessons learned and upcoming deliverables.',
    category: 'operations',
  },
  {
    id: 'ctf-night',
    title: 'Capture the Flag Night',
    start: setTime(addDays(today, 4), 18, 0),
    end: setTime(addDays(today, 4), 21, 0),
    location: 'Community hackerspace',
    description: 'Friendly challenge with community partners.',
    category: 'community',
  },
  {
    id: 'maintenance',
    title: 'Maintenance Window',
    start: setTime(addDays(today, -2), 22, 0),
    end: setTime(addDays(today, -1), 2, 0),
    location: 'Data center',
    description: 'Overnight updates for the lab environment.',
    category: 'maintenance',
  },
  {
    id: 'mentorship',
    title: 'Mentorship 1:1',
    start: setTime(addDays(today, 1), 10, 30),
    end: setTime(addDays(today, 1), 11, 30),
    location: 'Cafe conference area',
    description: 'Career growth check-in with mentee.',
    category: 'personal',
  },
  {
    id: 'focus-block',
    title: 'Research Focus Block',
    start: setTime(addDays(today, 3), 8, 0),
    end: setTime(addDays(today, 3), 11, 0),
    description: 'Deep work window reserved for kernel module write-up.',
    category: 'research',
  },
  {
    id: 'conference-prep',
    title: 'Conference Demo Recording',
    start: setTime(addDays(today, -4), 14, 0),
    end: setTime(addDays(today, -4), 16, 0),
    location: 'Studio',
    description: 'Record supporting material for upcoming security conference.',
    category: 'community',
  },
  {
    id: 'blue-team',
    title: 'Blue Team Planning',
    start: setTime(addDays(today, 6), 9, 0),
    end: setTime(addDays(today, 6), 10, 30),
    location: 'Strategy room',
    description: 'Outline playbooks for the next sprint.',
    category: 'operations',
  },
  {
    id: 'all-hands',
    title: 'Monthly All-hands',
    start: setTime(addDays(today, 7), 12, 0),
    end: setTime(addDays(today, 7), 13, 0),
    location: 'Main auditorium',
    description: 'Studio-wide status update and kudos session.',
    category: 'community',
  },
  {
    id: 'training',
    title: 'Purple Team Tabletop',
    start: setTime(addDays(today, -1), 15, 0),
    end: setTime(addDays(today, -1), 17, 0),
    location: 'Situation room',
    description: 'Simulated breach response rehearsal with both teams.',
    category: 'training',
  },
];
