export {
  ANALYTICS_CONSENT,
  type AnalyticsConsentValue,
  GA_ACTION,
  GA_CATEGORY,
  GA_EVENT_NAMES,
  GA_EVENTS,
  getAnalyticsConsent,
  initializeAnalytics,
  isAnalyticsEnabled,
  isAnalyticsEnvEnabled,
  logEvent,
  logGameEnd,
  logGameError,
  logGameStart,
  setAnalyticsConsent,
  trackEvent,
  trackPageview,
} from '../lib/analytics';
