export const NAVBAR_HEIGHT = 56;
export const NAVBAR_VERTICAL_PADDING = 8;
export const NAVBAR_BOTTOM_MARGIN = 8;
export const DESKTOP_TOP_PADDING = NAVBAR_HEIGHT + NAVBAR_VERTICAL_PADDING * 2 + NAVBAR_BOTTOM_MARGIN;
export const WINDOW_TOP_INSET = 8;
export const SNAP_BOTTOM_INSET = 28;
