export const NAVBAR_HEIGHT = 56;
export const NAVBAR_VERTICAL_PADDING = 0;
export const WINDOW_TOP_MARGIN = 2;
export const WINDOW_TOP_INSET = 8;
export const DESKTOP_TOP_PADDING =
  NAVBAR_HEIGHT +
  NAVBAR_VERTICAL_PADDING +
  WINDOW_TOP_MARGIN +
  WINDOW_TOP_INSET;
export const SNAP_BOTTOM_INSET = NAVBAR_HEIGHT + 2;
