import { DEFAULT_DESKTOP_FOLDERS } from '../data/desktopFolders';

export type CoreAppEntry = {
  id: string;
  title: string;
  icon?: string;
  disabled?: boolean;
  favourite?: boolean;
  desktop_shortcut?: boolean;
  isFolder?: boolean;
  resizable?: boolean;
  allowMaximize?: boolean;
  defaultWidth?: number;
  defaultHeight?: number;
};

const utilityList = [
  {
    id: 'qr',
    title: 'QR Tool',
    icon: '/themes/Yaru/apps/qr.svg',
    disabled: false,
    favourite: false,
    desktop_shortcut: true,
  },
  {
    id: 'ascii-art',
    title: 'ASCII Art',
    icon: '/themes/Yaru/apps/gedit.png',
    disabled: false,
    favourite: false,
    desktop_shortcut: true,
  },
  {
    id: 'clipboard-manager',
    title: 'Clipboard Manager',
    icon: '/themes/Yaru/apps/clipboard-manager.svg',
    disabled: false,
    favourite: false,
    desktop_shortcut: true,
  },
  {
    id: 'figlet',
    title: 'Figlet',
    icon: '/themes/Yaru/apps/gedit.png',
    disabled: false,
    favourite: false,
    desktop_shortcut: true,
  },
  {
    id: 'quote',
    title: 'Quote',
    icon: '/themes/Yaru/apps/quote.svg',
    disabled: false,
    favourite: false,
    desktop_shortcut: true,
  },
  {
    id: 'project-gallery',
    title: 'Project Gallery',
    icon: '/themes/Yaru/apps/project-gallery.svg',
    disabled: false,
    favourite: false,
    desktop_shortcut: true,
  },
  {
    id: 'input-lab',
    title: 'Input Lab',
    icon: '/themes/Yaru/apps/input-lab.svg',
    disabled: false,
    favourite: false,
    desktop_shortcut: true,
  },
  {
    id: 'subnet-calculator',
    title: 'Subnet Calculator',
    icon: '/themes/Yaru/apps/subnet-calculator.svg',
    disabled: false,
    favourite: false,
    desktop_shortcut: true,
  },
];

export const coreUtilities = utilityList;

// Default window sizing for games to prevent oversized frames
export const gameDefaults = {
  defaultWidth: 50,
  defaultHeight: 60,
};

// Games list used for the "Games" folder on the desktop
const gameList = [
  {
    id: '2048',
    title: '2048',
    icon: '/themes/Yaru/apps/2048.svg',
    disabled: false,
    favourite: false,
    desktop_shortcut: true,
    defaultWidth: 35,
    defaultHeight: 45,
  },
  {
    id: 'asteroids',
    title: 'Asteroids',
    icon: '/themes/Yaru/apps/asteroids.svg',
    disabled: false,
    favourite: false,
    desktop_shortcut: true,
  },
  {
    id: 'battleship',
    title: 'Battleship',
    icon: '/themes/Yaru/apps/battleship.svg',
    disabled: false,
    favourite: false,
    desktop_shortcut: true,
  },
  {
    id: 'blackjack',
    title: 'Blackjack',
    icon: '/themes/Yaru/apps/blackjack.svg',
    disabled: false,
    favourite: false,
    desktop_shortcut: true,
    ...gameDefaults,
  },
  {
    id: 'breakout',
    title: 'Breakout',
    icon: '/themes/Yaru/apps/breakout.svg',
    disabled: false,
    favourite: false,
    desktop_shortcut: true,
  },
  {
    id: 'car-racer',
    title: 'Car Racer',
    icon: '/themes/Yaru/apps/car-racer.svg',
    disabled: false,
    favourite: false,
    desktop_shortcut: true,
  },
  {
    id: 'lane-runner',
    title: 'Lane Runner',
    icon: '/themes/Yaru/apps/car-racer.svg',
    disabled: false,
    favourite: false,
    desktop_shortcut: true,
  },
  {
    id: 'checkers',
    title: 'Checkers',
    icon: '/themes/Yaru/apps/checkers.svg',
    disabled: false,
    favourite: false,
    desktop_shortcut: true,
  },
  {
    id: 'chess',
    title: 'Chess',
    icon: '/themes/Yaru/apps/chess.svg',
    disabled: false,
    favourite: false,
    desktop_shortcut: true,
  },
  // Simple placeholder implementation
  {
    id: 'connect-four',
    title: 'Connect Four',
    icon: '/themes/Yaru/apps/connect-four.svg',
    disabled: false,
    favourite: false,
    desktop_shortcut: true,
  },
  {
    id: 'frogger',
    title: 'Frogger',
    icon: '/themes/Yaru/apps/frogger.svg',
    disabled: false,
    favourite: false,
    desktop_shortcut: true,
  },
  {
    id: 'hangman',
    title: 'Hangman',
    icon: '/themes/Yaru/apps/hangman.svg',
    disabled: false,
    favourite: false,
    desktop_shortcut: true,
  },
  {
    id: 'memory',
    title: 'Memory',
    icon: '/themes/Yaru/apps/memory.svg',
    disabled: false,
    favourite: false,
    desktop_shortcut: true,
  },
  {
    id: 'minesweeper',
    title: 'Minesweeper',
    icon: '/themes/Yaru/apps/minesweeper.svg',
    disabled: false,
    favourite: false,
    desktop_shortcut: true,
  },
  {
    id: 'pacman',
    title: 'Pacman',
    icon: '/themes/Yaru/apps/pacman.svg',
    disabled: false,
    favourite: false,
    desktop_shortcut: true,
  },
  {
    id: 'platformer',
    title: 'Platformer',
    icon: '/themes/Yaru/apps/platformer.svg',
    disabled: false,
    favourite: false,
    desktop_shortcut: true,
  },
  {
    id: 'pong',
    title: 'Pong',
    icon: '/themes/Yaru/apps/pong.svg',
    disabled: false,
    favourite: false,
    desktop_shortcut: true,
  },
  {
    id: 'reversi',
    title: 'Reversi',
    icon: '/themes/Yaru/apps/reversi.svg',
    disabled: false,
    favourite: false,
    desktop_shortcut: true,
  },
  {
    id: 'simon',
    title: 'Simon',
    icon: '/themes/Yaru/apps/simon.svg',
    disabled: false,
    favourite: false,
    desktop_shortcut: true,
  },
  {
    id: 'snake',
    title: 'Snake',
    icon: '/themes/Yaru/apps/snake.svg',
    disabled: false,
    favourite: false,
    desktop_shortcut: true,
  },
  {
    id: 'sokoban',
    title: 'Sokoban',
    icon: '/themes/Yaru/apps/sokoban.svg',
    disabled: false,
    favourite: false,
    desktop_shortcut: true,
  },
  {
    id: 'solitaire',
    title: 'Solitaire',
    icon: '/themes/Yaru/apps/solitaire.svg',
    disabled: false,
    favourite: false,
    desktop_shortcut: true,
  },
  {
    id: 'tictactoe',
    title: 'Tic Tac Toe',
    icon: '/themes/Yaru/apps/tictactoe.svg',
    disabled: false,
    favourite: false,
    desktop_shortcut: true,
    ...gameDefaults,
  },
  {
    id: 'tetris',
    title: 'Tetris',
    icon: '/themes/Yaru/apps/tetris.svg',
    disabled: false,
    favourite: false,
    desktop_shortcut: true,
  },
  {
    id: 'tower-defense',
    title: 'Tower Defense',
    icon: '/themes/Yaru/apps/tower-defense.svg',
    disabled: false,
    favourite: false,
    desktop_shortcut: true,
  },
  {
    id: 'word-search',
    title: 'Word Search',
    icon: '/themes/Yaru/apps/word-search.svg',
    disabled: false,
    favourite: false,
    desktop_shortcut: true,
  },
  {
    id: 'wordle',
    title: 'Wordle',
    icon: '/themes/Yaru/apps/wordle.svg',
    disabled: false,
    favourite: false,
    desktop_shortcut: true,
  },
  {
    id: 'nonogram',
    title: 'Nonogram',
    icon: '/themes/Yaru/apps/nonogram.svg',
    disabled: false,
    favourite: false,
    desktop_shortcut: true,
  },
  {
    id: 'space-invaders',
    title: 'Space Invaders',
    icon: '/themes/Yaru/apps/space-invaders.svg',
    disabled: false,
    favourite: false,
    desktop_shortcut: true,
  },
  {
    id: 'sudoku',
    title: 'Sudoku',
    icon: '/themes/Yaru/apps/sudoku.svg',
    disabled: false,
    favourite: false,
    desktop_shortcut: true,
  },
  {
    id: 'flappy-bird',
    title: 'Flappy Bird',
    icon: '/themes/Yaru/apps/flappy-bird.svg',
    disabled: false,
    favourite: false,
    desktop_shortcut: true,
  },
  {
    id: 'candy-crush',
    title: 'Candy Crush',
    icon: '/themes/Yaru/apps/candy-crush.svg',
    disabled: false,
    favourite: false,
    desktop_shortcut: true,
  },
  {
    id: 'gomoku',
    title: 'Gomoku',
    icon: '/themes/Yaru/apps/gomoku.svg',
    disabled: false,
    favourite: false,
    desktop_shortcut: true,
  },
  {
    id: 'pinball',
    title: 'Pinball',
    icon: '/themes/Yaru/apps/pinball.svg',
    disabled: false,
    favourite: false,
    desktop_shortcut: true,
  },
];

export const coreGames = gameList.map((game) => ({ ...gameDefaults, ...game }));

const folderApps = DEFAULT_DESKTOP_FOLDERS.map((folder) => ({
  id: folder.id,
  title: folder.title,
  icon: folder.icon || '/themes/Yaru/system/folder.png',
  disabled: false,
  favourite: false,
  desktop_shortcut: true,
  isFolder: true,
  defaultWidth: 64,
  defaultHeight: 70,
}));

const coreApps = [
  ...folderApps,
  {
    id: 'firefox',
    title: 'Firefox',
    icon: '/themes/Yaru/apps/firefox.svg',
    disabled: false,
    favourite: true,
    desktop_shortcut: true,
  },
  {
    id: 'calculator',
    title: 'Calculator',
    icon: '/themes/Yaru/apps/calc.svg',
    disabled: false,
    favourite: false,
    desktop_shortcut: true,
    resizable: false,
    allowMaximize: false,
    defaultWidth: 28,
    defaultHeight: 50,
  },
  {
    id: 'terminal',
    title: 'Terminal',
    icon: '/themes/Yaru/apps/bash.svg',
    disabled: false,
    favourite: true,
    desktop_shortcut: true,
    resizable: true,
    defaultWidth: 68,
    defaultHeight: 72,
  },
  {
    // VSCode app uses a Stack iframe, so no editor dependencies are required
    id: 'vscode',
    title: 'Visual Studio Code',
    icon: '/themes/Yaru/apps/vscode.png',
    disabled: false,
    favourite: true,
    desktop_shortcut: true,
    defaultWidth: 85,
    defaultHeight: 85,
  },
  {
    id: 'x',
    title: 'X',
    icon: '/themes/Yaru/apps/x.png',
    disabled: false,
    favourite: true,
    desktop_shortcut: true,
  },
  {
    id: 'spotify',
    title: 'Spotify',
    icon: '/themes/Yaru/apps/spotify.svg',
    disabled: false,
    favourite: true,
    desktop_shortcut: true,
  },
  {
    id: 'youtube',
    title: 'YouTube',
    icon: '/themes/Yaru/apps/youtube.svg',
    disabled: false,
    favourite: true,
    desktop_shortcut: true,
  },
  {
    id: 'beef',
    title: 'BeEF',
    icon: '/themes/Yaru/apps/beef.svg',
    disabled: false,
    favourite: false,
    desktop_shortcut: true,
  },
  {
    id: 'about',
    title: 'About Alex',
    icon: '/themes/Yaru/system/user-home.png',
    disabled: false,
    favourite: true,
    desktop_shortcut: true,
  },
  {
    id: 'settings',
    title: 'Settings',
    icon: '/themes/Yaru/apps/gnome-control-center.svg',
    disabled: false,
    favourite: true,
    desktop_shortcut: true,
  },
  {
    id: 'files',
    title: 'Files',
    icon: '/themes/Yaru/system/folder.png',
    disabled: false,
    favourite: false,
    desktop_shortcut: true,
  },
  {
    id: 'resource-monitor',
    title: 'Resource Monitor',
    icon: '/themes/Yaru/apps/resource-monitor.svg',
    disabled: false,
    favourite: false,
    desktop_shortcut: true,
  },
  {
    id: 'screen-recorder',
    title: 'Screen Recorder',
    icon: '/themes/Yaru/apps/screen-recorder.svg',
    disabled: false,
    favourite: false,
    desktop_shortcut: true,
  },
  {
    id: 'ettercap',
    title: 'Ettercap',
    icon: '/themes/Yaru/apps/ettercap.svg',
    disabled: false,
    favourite: false,
    desktop_shortcut: true,
  },
  {
    id: 'ble-sensor',
    title: 'BLE Sensor',
    icon: '/themes/Yaru/apps/bluetooth.svg',
    disabled: false,
    favourite: false,
    desktop_shortcut: true,
  },
  {
    id: 'metasploit',
    title: 'Metasploit',
    icon: '/themes/Yaru/apps/metasploit.svg',
    disabled: false,
    favourite: false,
    desktop_shortcut: true,
  },
  {
    id: 'wireshark',
    title: 'Wireshark',
    icon: '/themes/Yaru/apps/wireshark.svg',
    disabled: false,
    favourite: false,
    desktop_shortcut: true,
  },
  {
    id: 'todoist',
    title: 'Todoist',
    icon: '/themes/Yaru/apps/todoist.png',
    disabled: false,
    favourite: false,
    desktop_shortcut: true,
  },
  {
    id: 'sticky_notes',
    title: 'Sticky Notes',
    icon: '/themes/Yaru/apps/sticky-notes.svg',
    disabled: false,
    favourite: false,
    desktop_shortcut: true,
  },
  {
    id: 'trash',
    title: 'Trash',
    icon: '/themes/Yaru/status/user-trash-symbolic.svg',
    disabled: false,
    favourite: false,
    desktop_shortcut: true,
  },
  {
    id: 'gedit',
    title: 'Contact Me',
    icon: '/themes/Yaru/apps/gedit.png',
    disabled: false,
    favourite: false,
    desktop_shortcut: true,
  },
  {
    id: 'converter',
    title: 'Converter',
    icon: '/themes/Yaru/apps/calc.svg',
    disabled: false,
    favourite: false,
    desktop_shortcut: true,
  },
  {
    id: 'kismet',
    title: 'Kismet',
    icon: '/themes/Yaru/apps/kismet.svg',
    disabled: false,
    favourite: false,
    desktop_shortcut: true,
  },
  {
    id: 'nikto',
    title: 'Nikto',
    icon: '/themes/Yaru/apps/nikto.svg',
    disabled: false,
    favourite: false,
    desktop_shortcut: true,
  },
  {
    id: 'autopsy',
    title: 'Autopsy',
    icon: '/themes/Yaru/apps/autopsy.svg',
    disabled: false,
    favourite: false,
    desktop_shortcut: true,
  },
  {
    id: 'plugin-manager',
    title: 'Plugin Manager',
    icon: '/themes/Yaru/apps/plugin-manager.svg',
    disabled: false,
    favourite: false,
    desktop_shortcut: true,
  },
  {    id: 'reaver',
    title: 'Reaver',
    icon: '/themes/Yaru/apps/reaver.svg',
    disabled: false,
    favourite: false,
    desktop_shortcut: true,
  },
  {
    id: 'nessus',
    title: 'Nessus',
    icon: '/themes/Yaru/apps/nessus.svg',
    disabled: false,
    favourite: false,
    desktop_shortcut: true,
  },
  {
    id: 'ghidra',
    title: 'Ghidra',
    icon: '/themes/Yaru/apps/ghidra.svg',
    disabled: false,
    favourite: false,
    desktop_shortcut: true,
  },
  {
    id: 'mimikatz',
    title: 'Mimikatz',
    icon: '/themes/Yaru/apps/mimikatz.svg',
    disabled: false,
    favourite: false,
    desktop_shortcut: true,
  },
  {
    id: 'mimikatz/offline',
    title: 'Mimikatz Offline',
    icon: '/themes/Yaru/apps/mimikatz.svg',
    disabled: false,
    favourite: false,
    desktop_shortcut: true,
  },
  {
    id: 'ssh',
    title: 'SSH Builder',
    icon: '/themes/Yaru/apps/ssh.svg',
    disabled: false,
    favourite: false,
    desktop_shortcut: true,
  },
  {
    id: 'http',
    title: 'HTTP Builder',
    icon: '/themes/Yaru/apps/http.svg',
    disabled: false,
    favourite: false,
    desktop_shortcut: true,
  },
  {
    id: 'html-rewriter',
    title: 'HTML Rewriter',
    icon: '/themes/Yaru/apps/html-rewriter.svg',
    disabled: false,
    favourite: false,
    desktop_shortcut: true,
  },
  {
    id: 'contact',
    title: 'Contact',
    icon: '/themes/Yaru/apps/contact.svg',
    disabled: false,
    favourite: false,
    desktop_shortcut: true,
  },
  {
    id: 'hydra',
    title: 'Hydra',
    icon: '/themes/Yaru/apps/hydra.svg',
    disabled: false,
    favourite: false,
    desktop_shortcut: true,
  },
  {
    id: 'nmap-nse',
    title: 'Nmap NSE',
    icon: '/themes/Yaru/apps/nmap-nse.svg',
    disabled: false,
    favourite: false,
    desktop_shortcut: true,
  },
  {
    id: 'weather',
    title: 'Weather',
    icon: '/themes/Yaru/apps/weather.svg',
    disabled: false,
    favourite: false,
    desktop_shortcut: true,
  },
  {
    id: 'weather-widget',
    title: 'Weather Widget',
    icon: '/themes/Yaru/apps/weather.svg',
    disabled: false,
    favourite: false,
    desktop_shortcut: true,
  },
  {
    id: 'serial-terminal',
    title: 'Serial Terminal',
    icon: '/themes/Yaru/apps/bash.svg',
    disabled: false,
    favourite: false,
    desktop_shortcut: true,
  },
  {
    id: 'radare2',
    title: 'Radare2',
    icon: '/themes/Yaru/apps/radare2.svg',
    disabled: false,
    favourite: false,
    desktop_shortcut: true,
  },
  {
    id: 'volatility',
    title: 'Volatility',
    icon: '/themes/Yaru/apps/volatility.svg',
    disabled: false,
    favourite: false,
    desktop_shortcut: true,
  },
  {
    id: 'hashcat',
    title: 'Hashcat',
    icon: '/themes/Yaru/apps/hashcat.svg',
    disabled: false,
    favourite: false,
    desktop_shortcut: true,
  },
  {
    id: 'msf-post',
    title: 'Metasploit Post',
    icon: '/themes/Yaru/apps/msf-post.svg',
    disabled: false,
    favourite: false,
    desktop_shortcut: true,
  },
  {
    id: 'evidence-vault',
    title: 'Evidence Vault',
    icon: '/themes/Yaru/apps/project-gallery.svg',
    disabled: false,
    favourite: false,
    desktop_shortcut: true,
  },
  {
    id: 'dsniff',
    title: 'dsniff',
    icon: '/themes/Yaru/apps/dsniff.svg',
    disabled: false,
    favourite: false,
    desktop_shortcut: true,
  },
  {
    id: 'john',
    title: 'John the Ripper',
    icon: '/themes/Yaru/apps/john.svg',
    disabled: false,
    favourite: false,
    desktop_shortcut: true,
  },
  {
    id: 'openvas',
    title: 'OpenVAS',
    icon: '/themes/Yaru/apps/openvas.svg',
    disabled: false,
    favourite: false,
    desktop_shortcut: true,
  },
  {
    id: 'recon-ng',
    title: 'Recon-ng',
    icon: '/themes/Yaru/apps/reconng.svg',
    disabled: false,
    favourite: false,
    desktop_shortcut: true,
  },
  {
    id: 'security-tools',
    title: 'Security Tools',
    icon: '/themes/Yaru/apps/project-gallery.svg',
    disabled: false,
    favourite: false,
    desktop_shortcut: true,
  },
  // Utilities are grouped separately
  ...coreUtilities,
  // Games are included so they appear alongside apps
  ...coreGames,
];

export default coreApps;

export const loadFullRegistry = async () => {
  const mod = await import('./registry-full');
  return {
    apps: Array.isArray(mod.default) ? mod.default : [],
    games: Array.isArray(mod.games) ? mod.games : [],
    utilities: Array.isArray(mod.utilities) ? mod.utilities : [],
    gameDefaults: mod.gameDefaults,
  };
};
