/**
 * Canonical design tokens shared between runtime components and build tooling.
 * Values mirror the CSS custom properties defined in styles/globals.css.
 */
/** @type {const} */
const themeTokens = {
  colors: {
    background: 'var(--color-bg)',
    text: 'var(--color-text)',
    primary: 'var(--color-primary)',
    secondary: 'var(--color-secondary)',
    accent: 'var(--color-accent)',
    muted: 'var(--color-muted)',
    surface: 'var(--color-surface)',
    inverse: 'var(--color-inverse)',
    border: 'var(--color-border)',
    terminal: 'var(--color-terminal)',
    dark: 'var(--color-dark)',
    focusRing: 'var(--color-focus-ring)',
    selection: 'var(--color-selection)',
    controlAccent: 'var(--color-control-accent)',
    kaliBlue: 'var(--kali-blue)',
    kaliBlueGlow: 'var(--kali-blue-glow)',
    kaliBg: 'var(--kali-bg)',
    panel: 'var(--kali-panel)',
    panelBorder: 'var(--kali-panel-border)',
    panelHighlight: 'var(--kali-panel-highlight)',
    ubuntu: {
      grey: 'var(--color-ub-grey)',
      warmGrey: 'var(--color-ub-warm-grey)',
      coolGrey: 'var(--color-ub-cool-grey)',
      orange: 'var(--color-ub-orange)',
      liteAubergine: 'var(--color-ub-lite-abrgn)',
      mediumAubergine: 'var(--color-ub-med-abrgn)',
      darkAubergine: 'var(--color-ub-drk-abrgn)',
      windowTitle: 'var(--color-ub-window-title)',
      gedit: {
        dark: 'var(--color-ub-gedit-dark)',
        light: 'var(--color-ub-gedit-light)',
        darker: 'var(--color-ub-gedit-darker)',
      },
      borderOrange: 'var(--color-ub-border-orange)',
      darkGrey: 'var(--color-ub-dark-grey)',
    },
    ubuntuTango: {
      grey: 'var(--color-ubt-grey)',
      warmGrey: 'var(--color-ubt-warm-grey)',
      coolGrey: 'var(--color-ubt-cool-grey)',
      blue: 'var(--color-ubt-blue)',
      green: 'var(--color-ubt-green)',
      geditOrange: 'var(--color-ubt-gedit-orange)',
      geditBlue: 'var(--color-ubt-gedit-blue)',
      geditDark: 'var(--color-ubt-gedit-dark)',
    },
    menu: {
      shell: 'color-mix(in srgb, var(--color-secondary) 88%, black 12%)',
      border: 'color-mix(in srgb, var(--color-border) 85%, black 15%)',
      columnStart: 'color-mix(in srgb, var(--color-secondary) 85%, black 15%)',
      columnMid: 'color-mix(in srgb, var(--color-secondary) 80%, black 20%)',
      columnEnd: 'color-mix(in srgb, var(--color-secondary) 74%, black 26%)',
      divider: 'color-mix(in srgb, var(--color-border) 82%, black 18%)',
      accent: 'color-mix(in srgb, var(--color-primary) 72%, white 28%)',
      accentStrong: 'color-mix(in srgb, var(--color-primary) 82%, white 18%)',
      accentMuted: 'color-mix(in srgb, var(--color-primary) 60%, white 40%)',
      ringOffset: 'color-mix(in srgb, var(--color-secondary) 65%, black 35%)',
      panel: 'color-mix(in srgb, var(--color-secondary) 90%, black 10%)',
      panelAlt: 'color-mix(in srgb, var(--color-secondary) 86%, black 14%)',
      panelHover: 'color-mix(in srgb, var(--color-secondary) 78%, black 22%)',
      search: 'color-mix(in srgb, var(--color-secondary) 88%, black 12%)',
      appIcon: 'color-mix(in srgb, var(--color-secondary) 84%, black 16%)',
      appActive: 'color-mix(in srgb, var(--color-secondary) 76%, black 24%)',
      appHover: 'color-mix(in srgb, var(--color-secondary) 72%, black 28%)',
      empty: 'color-mix(in srgb, var(--color-secondary) 82%, black 18%)',
      badge: 'color-mix(in srgb, var(--color-secondary) 70%, black 30%)',
      favorite: 'color-mix(in srgb, var(--color-secondary) 85%, black 15%)',
      favoriteHover: 'color-mix(in srgb, var(--color-secondary) 75%, black 25%)',
    },
    charts: {
      candidates: 'color-mix(in srgb, var(--game-color-success, #15803d) 85%, white 15%)',
      seconds: 'color-mix(in srgb, var(--game-color-secondary, #1d4ed8) 88%, white 12%)',
    },
  },
  spacing: {
    xs: 'var(--space-1)',
    sm: 'var(--space-2)',
    md: 'var(--space-3)',
    lg: 'var(--space-4)',
    xl: 'var(--space-5)',
    '2xl': 'var(--space-6)',
  },
  radii: {
    sm: 'var(--radius-sm)',
    md: 'var(--radius-md)',
    lg: 'var(--radius-lg)',
    xl: 'var(--radius-6)',
    pill: 'var(--radius-round)',
  },
  shadows: {
    soft: 'var(--shadow-2)',
    panel: '0 6px 20px rgba(0,0,0,.35)',
    menu: '0 20px 40px rgba(0,0,0,0.45)',
  },
  motion: {
    fast: 'var(--motion-fast)',
    medium: 'var(--motion-medium)',
    slow: 'var(--motion-slow)',
  },
  zIndex: {
    base: '0',
    raised: '10',
    dropdown: '50',
    popover: '60',
    overlay: '80',
    modal: '100',
    toast: '110',
    tooltip: '120',
  },
};

module.exports = themeTokens;
