name: Link Rot

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  link-rot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
      - run: yarn install --immutable --immutable-cache
      - run: yarn link-rot
