name: Redteam Tests

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
      - run: yarn install --immutable --immutable-cache
      - run: yarn redteam:generate
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: chore: update redteam tests
          title: 'chore: add redteam tests'
          branch: redteam/generated-tests
          labels: redteam
          assignees: unnippillil
