name: Static Export

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: yarn
      - run: yarn install --immutable --immutable-cache
      - run: yarn export
      - uses: actions/upload-artifact@v4
        with:
          name: static-site
          path: out
          if-no-files-found: error
